name: Build & Deploy React App
on: [push, workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install node modules
        run: yarn
      - name: Build project
        run: yarn run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: my-react-app-build
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get build folder
        uses: actions/download-artifact@v3
        with:
          name: my-react-app-build