name: Build react app and deploy to server
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
    # paths-ignore:
    #   - '.github/workflows/*' # не запускать воркфлоу при обновлении самих воркфлоу
jobs:
  Build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SERVER_KNOWN_HOSTS }}
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install node modules
        run: yarn
      - name: Test app
        run: yarn run test
      - name: Make build
        run: yarn build
      - name: Deploy to server (rsync over SSH)
        run: rsync -r ./build/ root@213.226.126.241:/var/www/html/
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: my-react-app-build
      - name: Get build folder
        uses: actions/download-artifact@v3
        with:
          name: my-react-app-build