name: Deploy React App
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install node modules
        run: yarn
      - name: Test app
        run: yarn run test
  Lint:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install node modules
        run: yarn
      - name: Lint app
        run: yarn run lint
  Build:
    needs: Lint
    strategy: 
      matrix:
        node-version: [16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: yarn
      - name: Build app
        run: yarn run build
      - name: Deploy
        run: echo Deploying...