name: Deploy React App
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install node modules
        run: yarn
      - name: Test app
        run: yarn run test
      - name: Lint app
        run: yarn run lint
      - name: Build app
        run: yarn run build
      - name: Deploy
        run: echo Deploying...